Section "InputClass"
	Identifier "SynPS/2 Synaptics Touchpad"
	MatchIsTouchpad "on"
	Driver "libinput"
	Option "Tapping" "on"
	Option "ClickMethod" "clickfinger"
	Option "NaturalScrolling" "true"
	Option "ScrollMethod" "twofinger"
	Option "TappingButtonMap" "lrm"
	Option "DisableWhileTyping" "true"
	Option "TappingDrag" "true"
	Option "TapButton1" "1"
	Option "TapButton2" "3"
	Option "TapButton3" "2"
	Option "MiddleEmulation" "true"
	Option "AccelSpeed" "0.2"
EndSection
