set -g  default-terminal "screen-256color"

# Set the prefix key to C-a
set -g prefix C-o
unbind C-b
bind C-o send-prefix

unbind %
bind , split-window -h 

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

#screen time lage
set -s escape-time 0

#start the window with 1
set -g base-index 1


bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
# bind-key -T copy-mode-vi 'y' send -X copy-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

unbind -T copy-mode-vi MouseDragEnd1Pane
#tmuxplugin

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'

#theme

set -g @plugin 'jimeh/tmux-themepack'

set -g @themepack 'powerline/block/cyan'


run '~/.tmux/plugins/tpm/tpm'
